-- ALL TABLES

--Supplier TABLE

CREATE TABLE SUPPLIER (
SID CHAR(5) PRIMARY KEY,				-- SUPPLIER ID Ex - S0001
SNAME VARCHAR(50) NOT NULL,
SADD VARCHAR(100) DEFAULT 'DELHI' NOT NULL,
SPHONE VARCHAR(15) UNIQUE NOT NULL,
EMAIL VARCHAR(50) UNIQUE NOT NULL)

DROP TABLE SUPPLIER;
DROP TABLE PRODUCT;

-- Product TABLE

CREATE TABLE PRODUCT (
PID CHAR(5) PRIMARY KEY,			-- PRODUCT ID Ex - P0001
PDESC VARCHAR(100) NOT NULL,
PRICE INT CHECK(PRICE >0) NOT NULL ,
CATEGORY CHAR(2) CHECK (CATEGORY IN('IT', 'HA', 'HC')) NOT NULL,   --IT, HA(HOME APPLIANCES), HC(HEALTH CARE) 
SID CHAR(5) REFERENCES SUPPLIER(SID))		-- SUPPLIER ID - SID 

CREATE TABLE CUST (
CID CHAR(5) PRIMARY KEY,				-- CUSTOMER CID C0001
CNAME VARCHAR(50) NOT NULL,
CADDRESS VARCHAR(100) NOT NULL,
CITY VARCHAR(30) NOT NULL,
PHONE VARCHAR(15) UNIQUE NOT NULL,
EMAIL VARCHAR(30) UNIQUE NOT NULL,
DOB DATE CHECK (DOB<01-01-2000) NOT NULL )

CREATE TABLE ORDERS (
OID CHAR(5)	PRIMARY KEY,				-- ORDER ID Ex - O0001
ODATE DATE NOT NULL,
CID CHAR(5) REFERENCES CUST(CID),
PID CHAR(5) REFERENCES PRODUCT(PID),
OQTY INT CHECK (OQTY >=1) NOT NULL)

Select * from ORDERS;

CREATE TABLE STOCK (
PID CHAR(5) REFERENCES PRODUCT(PID),		-- PRODUCT ID Ex- P0001 
SQTY INT CHECK(SQTY >=0) NOT NULL,			-- SQTY (STOCK QUANTITY)
ROL INT CHECK(ROL >0) NOT NULL,				-- ROL (REORDER LEVEL) limit for the next order purchase
MOQ INT CHECK (MOQ >=5) NOT NULL)			-- MOQ (MINIMUM ORDER QUANTITY) when the stock reaches the rol the minimum order placement 




